name: Digger

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:

  plan:
    name: Run digger
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@main
    - name: Generate
      uses: gruntwork-io/terragrunt-action@v2
      env:
        TG_DEVELOPMENT_GCP_PROJECT: ${{ secrets.TG_DEVELOPMENT_GCP_PROJECT }}
      with:
        tf_version: 1.11.2
        tg_version: 0.76.7
        tg_dir: live/development
        tg_command: '--experiment stacks stack generate'
    - name: Chmod
      run: sudo chown -R runner:docker live/development
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: digger run
      uses: diggerhq/digger@vLatest
      with:
        disable-locking: true
        setup-terraform: true
        setup-terragrunt: false
        terragrunt-version: 0.76.7
      env:
        TG_DEVELOPMENT_GCP_PROJECT: ${{ secrets.TG_DEVELOPMENT_GCP_PROJECT }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
