name: Digger

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  plan:
    name: Run digger
    runs-on: ubuntu-latest
    steps:
    - name: digger run
      uses: diggerhq/digger@vLatest
      with:
        disable-locking: true
        setup-terraform: true
        setup-terragrunt: true
        terragrunt-version: 0.76.7
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
